version: '3'

services:
  myflaskapp:
    build: .
    ports:
      - "80:80"
    depends_on:
      - mongodb
    networks:
      - mynetwork

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
